### PR TITLE
Compatibility custom voice + param wall thickness weighting

### LINKED ISSUE #141: [BUG] Crash when using custom voice sounds
**Describe the bug**
We got crashed when using custom sound files/ a patch for voices (e.g. https://mods.vintagestory.at/cobvoices)
We fixed that by copying some of the images and renamed them malevoice.png and femalevoice.png
Maybe you could add some sort of support for custom sound files.
As for now, we have uploaded a custom version for our server to the moddb, i hope thats ok. If not, we will remove the mod from the moddb.

**OS**
Windows

**Mod version**
v2.3.12

**Game version**
v1.20.3

**If using other mods, which?**
https://mods.vintagestory.at/cobvoices
and many others

**To Reproduce**
Install a custom sound mod

**Expected behavior**
Crashing with

[message.txt](https://github.com/user-attachments/files/18568696/message.txt)

**Screenshots**

**Additional context**

**Any logs should also be attached**

### PR DESCRIPTION
**Pull request by RomainOdeval**
- Fix #141 to allow RPVC to be "Custom Voice mods" compliant
- Allow to modify value of wall thickness weighting to adapt muffling effect (useful for RP servers)
- Update/clean code to prepare for the use of sound effects

### CODE REVIEW

**Comment by RomainOdeval** [comment]
Waiting megaphone icon to undraft

**Comment by RomainOdeval** [comment]
Megaphone icon updated. Still WIP by Faithfulshot but will be enough for now

**Comment by Ridderrasmus** [comment]
This will also need an entry in the readme for server owners for the variable wall thickness muffling.

File: src/Audio/Output/PlayerAudioSource.cs [hunk 1]
```diff
@@ -2,6 +2,7 @@
 using RPVoiceChat.Audio.Effects;
 using RPVoiceChat.DB;
 using RPVoiceChat.Gui;
+using RPVoiceChat.src.Audio.Effects;
```
Comment (Dmitry221060) [inline src/Audio/Output/PlayerAudioSource.cs:5]:
```suggestion
```

File: src/RPVoiceChatServer.cs [hunk 2]
```diff
@@ -39,6 +39,7 @@ public override void StartServerSide(ICoreServerAPI api)
             WorldConfig.Set(VoiceLevel.Shouting, WorldConfig.GetInt(VoiceLevel.Shouting));
             WorldConfig.Set("force-render-name-tags", WorldConfig.GetBool("force-render-name-tags", true));
             WorldConfig.Set("encode-audio", WorldConfig.GetBool("encode-audio", true));
+            WorldConfig.Set("wall-thickness-weighting", WorldConfig.GetFloat("wall-thickness-weighting", 1.5f));
```
Comment (Dmitry221060) [inline src/RPVoiceChatServer.cs:42]: Previous default value was 2. I don't mind reducing the strength of muffling but it's quite a noticeable change and is hard to justify
```suggestion
            WorldConfig.Set("wall-thickness-weighting", WorldConfig.GetFloat("wall-thickness-weighting", 2));
```

File: src/Audio/Effects/IntoxicatedEffect.cs [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+    public class IntoxicatedEffect : SoundEffect
+    {
+        protected float toxicRate;
+
+        public IntoxicatedEffect(int source) : base(source) {}
+
+        protected override void GenerateEffect()
+        {
+            float pitch = toxicRate <= 0.2 ? 1 : 1 - (toxicRate / 5);
+            OALW.Source(source, ALSourcef.Pitch, pitch);
```
Comment (Dmitry221060) [inline src/Audio/Effects/IntoxicatedEffect.cs:21]: Changing pitch also changes audio playback speed, this proved to be an issue in all of our testing, causing overflow of circular audio buffer. More advanced implementation is required, for now this can be replaced with a comment to avoid accidental usage of this effect

File: src/Audio/Effects/IntoxicatedEffect.cs [hunk 4]
```diff
@@ -0,0 +1,29 @@
+﻿using System;
+using System.Collections.Generic;
+using System.Linq;
+using System.Text;
+using System.Threading.Tasks;
+using OpenTK.Audio.OpenAL;
+using RPVoiceChat.Audio;
+using RPVoiceChat.Audio.Effects;
+
+namespace RPVoiceChat.src.Audio.Effects
```
Comment (Dmitry221060) [inline src/Audio/Effects/IntoxicatedEffect.cs:10]:
```suggestion
namespace RPVoiceChat.Audio.Effects
```

File: src/Audio/Output/PlayerAudioSource.cs [hunk 5]
```diff
@@ -10,6 +11,7 @@
 using Vintagestory.API.Common;
 using Vintagestory.API.Common.Entities;
 using Vintagestory.API.MathTools;
+using Vintagestory.GameContent;
```
Comment (Dmitry221060) [inline src/Audio/Output/PlayerAudioSource.cs:14]: PlayerAudioSource shouldn't know about game content, it's not its area of responsibility

File: src/Audio/Output/PlayerAudioSource.cs [hunk 6]
```diff
@@ -98,38 +103,57 @@ public void UpdatePlayer()
...
+                BlockPos plrpos = new BlockPos();
+                plrpos.Set((int)speakerPos.X, (int)speakerPos.Y, (int)speakerPos.Z);
+                Room room = capi.ModLoader.GetModSystem<RoomRegistry>().GetRoomForPosition(plrpos);
+                // Check whether it is a proper room, or something like a room i.e. with a roof, for example a natural cave
+                bool inEnclosedRoom = room.ExitCount == 0 || room.SkylightCount < room.NonSkylightCount;
+                if (inEnclosedRoom) 
+                {
+                    reverbEffect = reverbEffect ?? new ReverbEffect(source);
+                    reverbEffect.Start();
+                }
```
Comment (Dmitry221060) [inline src/Audio/Output/PlayerAudioSource.cs:133]: Implementation details should be abstracted away to utility function or some delegated class, PlayerAudioSource is a high-level class that shouldn't know nor handle any of this

Comment (Dmitry221060) [inline src/Audio/Output/PlayerAudioSource.cs:133]: Implementation details should be abstracted away to utility function or some delegated class, PlayerAudioSource is a high-level class that shouldn't know nor handle any of this

**Review by Dmitry221060 — CHANGES_REQUESTED** [review]

File: src/Audio/Effects/ReverbEffect.cs
[the remark this answers is not in the document]
Comment (RomainOdeval) [reply src/Audio/Effects/ReverbEffect.cs:1]: Same as https://github.com/Ridderrasmus/RPVoiceChat/pull/143#discussion_r1938291851

File: src/Audio/Effects/SoundEffect.cs [hunk 7]
```diff
@@ -0,0 +1,42 @@
+using Cairo;
```
[the remark this answers is not in the document]
Comment (RomainOdeval) [reply src/Audio/Effects/SoundEffect.cs:1]: Done 👍

File: src/Audio/Effects/UnstableEffect.cs [hunk 8]
```diff
@@ -0,0 +1,18 @@
+﻿using System;
+using System.Collections.Generic;
+using System.Linq;
+using System.Text;
+using System.Threading.Tasks;
+using RPVoiceChat.Audio.Effects;
+
+namespace RPVoiceChat.src.Audio.Effects
```
[the remark this answers is not in the document]
Comment (RomainOdeval) [reply src/Audio/Effects/UnstableEffect.cs:8]: Done 👍

File: src/Audio/Effects/SoundEffect.cs [hunk 9]
```diff
@@ -0,0 +1,42 @@
...
+        public bool IsEnabled { get; set; } = false;
+
+        protected SoundEffect(int source)
+        {
+            this.source = source;
+            this.nullEffect = ALC.EFX.GenEffect();
+            GenerateEffect();
+        }
+
+        public void Start()
```
[the remark this answers is not in the document]
Comment (RomainOdeval) [reply src/Audio/Effects/SoundEffect.cs:22]: Done 👍

File: src/Audio/Effects/SoundEffect.cs [hunk 10]
```diff
@@ -0,0 +1,42 @@
...
+        protected int slot;
+        private int nullEffect;
+
+        public bool IsEnabled { get; set; } = false;
+
+        protected SoundEffect(int source)
+        {
+            this.source = source;
+            this.nullEffect = ALC.EFX.GenEffect();
+            GenerateEffect();
```
[the remark this answers is not in the document]
Comment (RomainOdeval) [reply src/Audio/Effects/SoundEffect.cs:19]: something like that ? 
```protected SoundEffect(int source, int effect)
{
    this.source = source;
    this.nullEffect = ALC.EFX.GenEffect();
    this.effect = effect;
    GenerateEffect();
}```

File: src/Audio/Output/PlayerAudioSource.cs (hunk 1 above)
Comment (RomainOdeval) [reply src/Audio/Output/PlayerAudioSource.cs:5]: Done 👍

File: src/Audio/Effects/IntoxicatedEffect.cs (hunk 4 above)
Comment (RomainOdeval) [reply src/Audio/Effects/IntoxicatedEffect.cs:10]: Done 👍

File: src/RPVoiceChatServer.cs (hunk 2 above)
Comment (RomainOdeval) [reply src/RPVoiceChatServer.cs:42]: After testing, "2" had no significant effect with one layer of blocks.
The idea was to have a default value that affect significantly sound with only one layer because most players will have only "one layer" walls.
I can undo it, if you want.

File: README.md [hunk 11]
```diff
@@ -60,6 +60,7 @@ You can also use `/rpvc [command]` to access world-specific settings:
 - `info` - Displays current audio distances and states of toggles.
 - `forcenametags` - If you use mods that hide player name tags you can disable this setting to keep them hidden. The default value is `true`.
 - `encodeaudio` - If you encounter distorted/out of order audio you can disable thus setting and see if it helps. **Be aware that this will drastically increase bandwidth usage for everyone on the server.** The default value is `true`.
+- `wtw` - Sets the weighting applied on wall thickness calculation for muffling. Values below 1 will increase muffling effect, values upper 1 will reduced it. The default value is `1.5`.
```
[the remark this answers is not in the document]
Comment (RomainOdeval) [reply README.md:63]: After testing, "2" had no significant effect with one layer of blocks.
The idea was to have a default value that affect significantly sound with only one layer because most players will have only "one layer" walls.
I can undo it, if you want.

File: src/Audio/Effects/IntoxicatedEffect.cs (hunk 3 above)
Comment (RomainOdeval) [reply src/Audio/Effects/IntoxicatedEffect.cs:21]: Alert added 👍

File: src/Audio/Output/PlayerAudioSource.cs (hunk 6 above)
Comment (RomainOdeval) [reply src/Audio/Output/PlayerAudioSource.cs:133]: What do you think about a function into LocationUtils ?
For me, it's "am i in an area where it can have reverb effect" ?

File: src/Audio/Effects/SoundEffect.cs (hunk 10 above)
[the remark this answers is not in the document]
Comment (Dmitry221060) [reply src/Audio/Effects/SoundEffect.cs:19]:
```csharp
protected SoundEffect(int source, int effect)
{
    this.source = source;
    this.nullEffect = ALC.EFX.GenEffect();
    this.effect = GenerateEffect();
}
```
And make GenerateEffect return int

File: src/RPVoiceChatServer.cs (hunk 2 above)
Comment (Dmitry221060) [reply src/RPVoiceChatServer.cs:42]: I believe it was decided to not muffle the sound too much because on RP servers when people have conversation and, for example, a store owner goes in a back room to fetch something it would be too inaudible and overall inconvenient to have. Some decorations and non-full blocks will also cause muffling, so it would be weird if a cup sitting on the table had significant impact on player's voice
Now that it is adjustable people can increase/lower the muffling strength if they want, so I suggest we keep the default at 2 as it already was

Comment (RomainOdeval) [reply src/RPVoiceChatServer.cs:42]: Ok ! done 👍

File: src/Audio/Output/PlayerAudioSource.cs (hunk 6 above)
Comment (Dmitry221060) [reply src/Audio/Output/PlayerAudioSource.cs:133]: Yeah, a method in LocationUtils would be fine. Alternatively it can also be a part of ReverbEffect, but that will blur its responsibility so some general utility function is preferable to it

File: README.md (hunk 11 above)
[the remark this answers is not in the document]
Comment (RomainOdeval) [reply README.md:63]: See https://github.com/Ridderrasmus/RPVoiceChat/pull/143#discussion_r1938299735

File: src/Audio/Effects/SoundEffect.cs (hunk 10 above)
[the remark this answers is not in the document]
Comment (RomainOdeval) [reply src/Audio/Effects/SoundEffect.cs:19]: OK ! Done 👍

File: src/Audio/Output/PlayerAudioSource.cs (hunk 6 above)
Comment (RomainOdeval) [reply src/Audio/Output/PlayerAudioSource.cs:133]: Done 👍

File: src/Audio/Output/PlayerAudioSource.cs (hunk 5 above)
Comment (RomainOdeval) [reply src/Audio/Output/PlayerAudioSource.cs:14]: Done 👍

File: src/Audio/Effects/IntoxicatedEffect.cs [hunk 12]
```diff
@@ -0,0 +1,26 @@
...
+        public IntoxicatedEffect(int source) : base(source) {}
+
+        protected override int GenerateEffect()
+        {
+            // WARNING : changing pitch also changes audio playback speed, causing overflow of circular audio buffer.
+            // More advanced implementation is required before using this effect
+            float pitch = toxicRate <= 0.2 ? 1 : 1 - (toxicRate / 5);
+            OALW.Source(source, ALSourcef.Pitch, pitch);
+
+            return (int)EffectType.PitchShifter;
```
Comment (Dmitry221060) [inline src/Audio/Effects/IntoxicatedEffect.cs:18]: `SoundEffect.effect` is an internal ID of the OpenAL effect, you get it when you generate new OpenAl effect with `ALC.EFX.GenEffect()`
IntoxicatedEffect doesn't use any effects as of now so we can just throw `NotImplementedException`

File: src/Audio/Effects/ReverbEffect.cs [hunk 13]
```diff
@@ -23,7 +22,8 @@ public ReverbEffect(int source)
             ALC.EFX.Effect(effect, EffectFloat.ReverbGain, 0.23f);
 
             ALC.EFX.AuxiliaryEffectSlot(slot, EffectSlotInteger.Effect, effect);
-            ALC.EFX.Source(source, EFXSourceInteger3.AuxiliarySendFilter, slot, 0, 0);
+
+            return (int)EffectType.Reverb;
```
Comment (Dmitry221060) [inline src/Audio/Effects/ReverbEffect.cs:26]: `SoundEffect.effect` is an internal ID of the OpenAL effect
```suggestion
            return effect;
```

File: src/Audio/Effects/UnstableEffect.cs [hunk 14]
```diff
@@ -0,0 +1,14 @@
...
+
+namespace RPVoiceChat.Audio.Effects
+{
+    public class UnstableEffect : SoundEffect
+    {
+        public UnstableEffect(int source) : base(source) { }
+
+        protected override int GenerateEffect()
+        {
+            return (int)EffectType.Distortion;
```
Comment (Dmitry221060) [inline src/Audio/Effects/UnstableEffect.cs:11]: `SoundEffect.effect` is an internal ID of the OpenAL effect, you get it when you generate new OpenAl effect with `ALC.EFX.GenEffect()`
`UnstableEffect` doesn't use any effects as of now so we can just throw `NotImplementedException`

**Review by Dmitry221060 — CHANGES_REQUESTED** [review]

File: src/Audio/Effects/UnstableEffect.cs (hunk 14 above)
Comment (RomainOdeval) [reply src/Audio/Effects/UnstableEffect.cs:11]: Done 👍

File: src/Audio/Effects/ReverbEffect.cs (hunk 13 above)
Comment (RomainOdeval) [reply src/Audio/Effects/ReverbEffect.cs:26]: Done 👍

**Review by Dmitry221060 — APPROVED** [review]
LGTM :+1:
